name: Deploy to cpanel
on: 
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on:  ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      # Deploy to cPanel
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.mithames.co.ke
          username: deeper@mithames.co.ke
          password: ${{ secrets.SFTP_PASSWORD }}
          protocol: ftps
          server-dir: /deeper
          
      